; KaiMi Studio — Inno Setup Configuration
; Requires Inno Setup 6.3+
; Installer metadata is generated from core.version by build.py
; (see installer_metadata.iss). Do not hand-edit the defines below.
#include "installer_metadata.iss"

[Setup]
AppId={{6774c03f-8d3b-475a-ac4c-abed65376271}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=installer_output
OutputBaseFilename=KaiMiStudio-Setup-{#MyAppVersion}
SetupIconFile=resources\branding\app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
; KaiMi Studio branded wizard images (regenerated by build.py from logo.png).
WizardImageFile=resources\branding\installer_wizard.bmp
WizardSmallImageFile=resources\branding\installer_wizard_small.bmp
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
VersionInfoVersion={#MyAppVersion}.0
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription={#MyAppName} Setup
VersionInfoCopyright={#MyAppCopyright}
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
CloseApplications=force
CloseApplicationsFilter={#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startmenuicon"; Description: "Create a Start Menu shortcut"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "dist\KaiMi Studio\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

; No blanket [UninstallDelete] of {app}: KaiMi Studio stores user-created
; projects and exports under the app folder at runtime. The [Code] section
; sweeps leftover app files on uninstall while preserving those directories.

[Code]
var
  InstallPercentLabel: TNewStaticText;

// True for runtime-created directories that hold user data (projects and
// per-project exports). They must survive uninstallation; the app's own
// installed files are removed by the uninstaller automatically.
function IsUserDataDir(const DirName: string): Boolean;
begin
  Result := (CompareText(DirName, 'projects') = 0)
         or (CompareText(DirName, 'exports') = 0);
end;

// Recursively delete every file and folder below Path except directories
// that hold user data ('projects' / 'exports' at any nesting level).
procedure DeleteAppTreeExceptUserData(const Path: string);
var
  FindRec: TFindRec;
  ChildPath: string;
begin
  if FindFirst(Path + '\*', FindRec) then
  begin
    try
      repeat
        if (FindRec.Name <> '.') and (FindRec.Name <> '..') then
        begin
          ChildPath := Path + '\' + FindRec.Name;
          if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY) <> 0 then
          begin
            if not IsUserDataDir(FindRec.Name) then
            begin
              DeleteAppTreeExceptUserData(ChildPath);
              RemoveDir(ChildPath);
            end;
          end
          else
            DeleteFile(ChildPath);
        end;
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

procedure CurUninstallStepChanged(CurStep: TUninstallStep);
begin
  // After the uninstaller has removed every installed file, sweep the
  // runtime leftovers (logs, settings, cache) while preserving the
  // user-created projects and exports directories.
  if CurStep = usPostUninstall then
    DeleteAppTreeExceptUserData(ExpandConstant('{app}'));
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
end;

// The on-screen percentage is driven by the installer engine's own real
// progress (CurInstallProgressChanged). It is never faked with a timer.
procedure UpdateInstallPercent(const APercent: Integer);
begin
  if InstallPercentLabel <> nil then
    InstallPercentLabel.Caption := Format('%d%%', [APercent]);
end;

procedure CurInstallProgressChanged(CurProgress, MaxProgress: Integer);
begin
  if MaxProgress > 0 then
    UpdateInstallPercent((CurProgress * 100) div MaxProgress);
end;

procedure InitializeWizard();
begin
  InstallPercentLabel := TNewStaticText.Create(WizardForm);
  InstallPercentLabel.Parent := WizardForm.InstallingPage;
  InstallPercentLabel.Caption := '';
  InstallPercentLabel.Visible := False;
end;

procedure CurPageChanged(CurPageID: Integer);
var
  Gap: Integer;
begin
  if CurPageID = wpInstalling then
  begin
    Gap := 10;
    InstallPercentLabel.Width := WizardForm.ProgressGauge.Width;
    InstallPercentLabel.Height := 22;
    InstallPercentLabel.Left := WizardForm.ProgressGauge.Left;
    InstallPercentLabel.Top := WizardForm.ProgressGauge.Top
      + WizardForm.ProgressGauge.Height + Gap;
    InstallPercentLabel.Alignment := taCenter;
    InstallPercentLabel.Visible := True;
    // Keep the current-file label below the percentage so nothing overlaps.
    WizardForm.FilenameLabel.Top := InstallPercentLabel.Top
      + InstallPercentLabel.Height + Gap;
  end;
end;
