; KaiMi Studio — Inno Setup Configuration
; Requires Inno Setup 6.3+
; Installer metadata is generated from core.version by build.py
; (see installer_metadata.iss). Do not hand-edit the defines below.
#include "installer_metadata.iss"

[Setup]
AppId={{6774c03f-8d3b-475a-ac4c-abed65376271}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=installer_output
OutputBaseFilename=KaiMiStudio-Setup-{#MyAppVersion}
SetupIconFile=resources\branding\app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
; KaiMi Studio branded wizard images (regenerated by build.py from logo.png).
WizardImageFile=resources\branding\installer_wizard.bmp
WizardSmallImageFile=resources\branding\installer_wizard_small.bmp
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridingOwnedFolder
VersionInfoVersion={#MyAppVersion}.0
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription={#MyAppName} Setup
VersionInfoCopyright={#MyAppCopyright}
VersionInfoProductName={#MyAppName}
VersionInfoProductVersion={#MyAppVersion}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
CloseApplications=force
CloseApplicationsFilter={#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startmenuicon"; Description: "{cm:CreateProgramGroup}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checked

[Files]
Source: "dist\KaiMi Studio\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
Type: filesandordirs; Name: "{localappdata}\KaiMi"

[Code]
var
  InstallPercentLabel: TNewStaticText;

function InitializeSetup(): Boolean;
begin
  Result := True;
end;

// The on-screen percentage is driven by the installer engine's own real
// progress (CurInstallProgressChanged). It is never faked with a timer.
procedure UpdateInstallPercent(const APercent: Integer);
begin
  if InstallPercentLabel <> nil then
    InstallPercentLabel.Caption := Format('%d%%', [APercent]);
end;

procedure CurInstallProgressChanged(CurProgress, MaxProgress: Integer);
begin
  if MaxProgress > 0 then
    UpdateInstallPercent((CurProgress * 100) div MaxProgress);
end;

procedure InitializeWizard();
begin
  InstallPercentLabel := TNewStaticText.Create(WizardForm);
  InstallPercentLabel.Parent := WizardForm.InstallingPage;
  InstallPercentLabel.Caption := '';
  InstallPercentLabel.Visible := False;
end;

procedure CurPageChanged(CurPageID: Integer);
var
  Gap: Integer;
begin
  if CurPageID = wpInstalling then
  begin
    Gap := 10;
    InstallPercentLabel.Width := WizardForm.ProgressGauge.Width;
    InstallPercentLabel.Height := 22;
    InstallPercentLabel.Left := WizardForm.ProgressGauge.Left;
    InstallPercentLabel.Top := WizardForm.ProgressGauge.Top
      + WizardForm.ProgressGauge.Height + Gap;
    InstallPercentLabel.Alignment := taCenter;
    InstallPercentLabel.Visible := True;
    // Keep the current-file label below the percentage so nothing overlaps.
    WizardForm.FilenameLabel.Top := InstallPercentLabel.Top
      + InstallPercentLabel.Height + Gap;
  end;
end;
